/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Img: typeof import('./src/components/Img.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
